on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      environment-name: dev
      environment-type: development
    secrets:
      aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      openai-api-key: ${{ secrets.OPENAI_API_KEY }}