on:
  push:
    branches:
      - feature/**

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      api-stack-name: askpg-${{ github.actor }}
      environment-name: ${{ github.ref_name }}
      environment-type: development
      is-feature-branch: true
    secrets:
      aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      openai-api-key: ${{ secrets.OPENAI_API_KEY }}